# FinOps Application Buckets
source.bucket=emr-finops-metrics-db-dev
source.prefix=test/
target.bucket=emr-finops-metrics-db-dev
target.prefix=test-fixed/

# AWS Connection Settings
quarkus.s3.aws.region=us-east-1
quarkus.s3.aws.credentials.type=default
quarkus.s3.devservices.enabled=false

# Reduce known noisy warnings during parquet rewrite runs.
quarkus.log.category."org.apache.hadoop.util.NativeCodeLoader".level=ERROR
quarkus.log.category."org.apache.parquet.CorruptStatistics".level=ERROR

